language: haskell

env:
  matrix:
    - HPVER=2012.4.0.0
    - HPVER=2013.2.0.0
    - GHCVER=7.4.2
    - GHCVER=7.6.3
    - GHCVER=7.8.2
    - GHCVER=head CABALVER=1.22
  global:
    - CABALVER=1.20

matrix:
  allow_failures:
    - env: GHCVER=head CABALVER=1.22
    - env: GHCVER=7.4.2

before_install:
  - source travis/scripts/set_env.sh
  - ./travis/scripts/before_install.sh

install: ./travis/scripts/install.sh

script: ./travis/scripts/script.sh